version: '3.0'

services:
  grafana:
    container_name: 'fau-sparql-datasource'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_DEFAULT_APP_MODE=development
      - GF_ALLOW_LOADING_UNSIGNED_PLUGINS=fau-sparql-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=fau-sparql-datasource
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/fau-sparql-datasource
      - ./provisioning:/etc/grafana/provisioning
